/**
 * Global setup for error message testing
 * 
 * This ensures the test environment is properly configured
 * and creates necessary directories for test artifacts.
 */

const fs = require('fs');
const path = require('path');

async function globalSetup() {
  console.log('🔧 Setting up error message audit test environment...');
  
  // Create test results directory
  const resultsDir = path.join(process.cwd(), 'test-results');
  if (!fs.existsSync(resultsDir)) {
    fs.mkdirSync(resultsDir, { recursive: true });
    console.log('✅ Created test-results directory');
  }

  // Create a test summary file
  const summaryFile = path.join(resultsDir, 'audit-summary.md');
  const summaryContent = `# Error Messages Audit - Maslow AI Rebranding

## Test Summary
**Date**: ${new Date().toISOString()}
**Purpose**: Verify all user-facing error messages use Maslow AI branding instead of HeyGen

## Test Categories
1. ✅ API Error Responses (401, 403, 404, 500, 503)
2. ✅ Network Error Handling  
3. ✅ UI Component Error Messages
4. ✅ Toast Notifications
5. ✅ Store Error Handling
6. ✅ Page Content Audit

## Expected Results
- ❌ Zero "HeyGen" references in user-facing content
- ✅ "Maslow AI" branding in appropriate error messages
- ✅ Generic service terminology where appropriate

## Screenshots Generated
- \`error-401-authentication.png\` - Authentication error messages
- \`error-503-service-unavailable.png\` - Service unavailable messages  
- \`error-network-failure.png\` - Network error handling
- \`toast-messages-check.png\` - Toast notification messages
- \`page-content-audit.png\` - Full page content scan
- \`api-error-responses.png\` - API error response structure
- \`complete-error-collection.png\` - All collected error messages

---
*Generated by automated error message audit*
`;

  fs.writeFileSync(summaryFile, summaryContent);
  console.log('✅ Created audit summary file');

  console.log('🚀 Setup complete - ready to run error message audit tests');
}

module.exports = globalSetup;